<h3>Ferramentas Disponíveis</h3>
<dl>
    <dt><a href="<?php echo $this->Url(array('module' => 'tools', 'controller'=>'model'))?>">Model</a></dt>
    <dd>Gerador de Model e Database Abstract</dd>
    <dt><a href="<?php echo $this->Url(array('module' => 'tools', 'controller'=>'model', 'action'=>'sql'))?>">Sql</a></dt>
    <dd>Consulta SQL diretamente da aplicação</dd>
    <dt><a href="<?php echo $this->Url(array('module' => 'tools', 'controller'=>'migrar', 'action'=>'index'))?>">Migrar</a></dt>
    <dd>Migrar ACL para versão nova</dd>
</dl>
