<?php
echo $this->form;
?>
<script type="text/javascript">var baseUrl = '<?php echo $this->baseUrl(); ?>';</script>
<script src="<?php echo $this->baseUrl(); ?>/js/relatorios.gerenciais.js"  type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/relatorios.dadosinstitucionais.js"  type="text/javascript"></script>

<?php
if($this->rsRegistros){
    echo $this->rsRegistros;
}
?>
