<div id='preLoader'></div>
<script type="text/javascript">var baseUrl = '<?php echo $this->baseUrl(); ?>';</script>
<style type="text/css">
    
    #conteudo fieldset.checkbox {
		border: none;
		padding: 0;
		margin: 0;
		font-weight: bold;
	}
    
</style>
<div>
    <?php
echo $this->form;
	?>
</div>
<script	src="<?php echo $this->baseUrl(); ?>/js/financeiro.bolsa.js" type="text/javascript"></script>
