<script type="text/javascript">
var baseUrl = '<?php echo $this->baseUrl(); ?>';

</script>
<?php

echo $this->form->getElement('NU_SEQ_TURMA');
echo $this->form->getElement('htmlTurma');
echo "<br/>";
?>
<fieldset>
	<legend>Cursistas</legend>
	<?php
echo $this->grid;
	?>
</fieldset>

<div id="divBotoes" class="barraBtsAcoes">
<?php
echo $this->form->getElement('confirmarNotificacao');
echo $this->form->getElement('cancelar');
?>
</div>
<script src="<?php echo $this->baseUrl(); ?>/js/secretaria.notificarcursista.js" type="text/javascript"></script>
