<script type="text/javascript">var baseUrl = '<?php echo $this->baseUrl(); ?>';</script>
<script src="<?php echo $this->baseUrl(); ?>/js/jquery.maskMoney.js"  type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/funcoes.js"  type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/jquery.maskedinput.js"  type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/util.js"  type="text/javascript"></script>
<?php
echo $this->form;
?>
