<div id='preLoader'></div>
<script type="text/javascript">var baseUrl = '<?php echo $this->baseUrl(); ?>';</script>
<style type="text/css">
.btnPesquisar {
	margin-left: 240px;
	position: absolute;
}

#form span {
	width: 140px !important;
}

#form span.campoRequerido {
	width: 125px !important;
}
</style>
<div class="tela">
	<?php
echo $this->form;
	?>
	<form>
		<div class="notas">Campos obrigatórios</div>
	</form>
</div>
<div id="html" style="display: none;">
	<?php
echo $this->formlimpo;
	?>
</div>
<a name="fim"></a>
<script	src="<?php echo $this->baseUrl(); ?>/js/manutencao.curso.cadastro.js" type="text/javascript"></script>
