<script type="text/javascript">var baseUrl = '<?php echo $this->baseUrl(); ?>';</script>
<style type="text/css">
	#preLoader {
	    width: 100%;
	    height: 100%;
	    margin: 0;
	    padding: 0;
	    background: #fff url(<?php echo $this->baseUrl(); ?>/img/ajax-loader.gif) no-repeat center center;
	    opacity: 0.60;
	    filter: alpha(opacity = 30);
	    -moz-opacity: 0.30;
	    position: absolute;
	    z-index: 999999;
	    display: none;
	}

	.errors li {
		width: 400px;
		color: #FF0000;
	}
	
</style>
<?php
echo $this->formFilter;
?>
<form>
	<div class="notas">Campo obrigatório</div>
</form>
<br clear="all" />
<?php
echo $this->grid;
?>
<script src="<?php echo $this->baseUrl(); ?>/js/util.js"  type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/manutencao.usuario.outras.atividades.js"  type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/manutencao.usuario.js"  type="text/javascript"></script>
