<div id='preLoader'></div>
<script type="text/javascript">var baseUrl = '<?php echo $this->baseUrl(); ?>';</script>
<style type="text/css">
    .btnPesquisar {
    	margin-left: 240px;
    	position: absolute;
    	
	}
	
	#form span{
	    width: 140px !important;
	}

	#form span.campoRequerido{
	    width: 125px !important;
	}
	
	#popup_content {
		width: 485px;
	}
	
</style>

<div>
	<div id="divErroFA" class="msgErro" style="display:none">
		<h3>Erro</h3>
		<p>O formulário possui informações incompletas ou inválidas.</p>
		<p id="camposErro"></p>
	</div>
    <?php
echo $this->form;
echo '<div class="notas">Campo obrigatório</div>'
	?>
</div>
<script
	src="<?php echo $this->baseUrl(); ?>/js/manutencao.formacao.academica.js"
	type="text/javascript"></script>
