<?php echo $this->form; ?>
<?php echo $this->grid; ?>
<style type="text/css">
    #preLoader {
        width: 100%;
        height: 100%;
        margin: 0;
        padding: 0;
        background: #fff url(<?php echo $this->baseUrl(); ?>/img/ajax-loader.gif) no-repeat center center;
        opacity: 0.60;
        filter: alpha(opacity = 30);
        -moz-opacity: 0.30;
        position: absolute;
        z-index: 999999;
        display: none;
    }

    .errors li {
        width: 400px;
        color: #FF0000;
    }
</style>
<script type="text/javascript">var baseUrl = '<?php echo $this->baseUrl(); ?>';</script>
<script src="<?php echo $this->baseUrl(); ?>/js/util.js"  type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/relatorios.dadosdoscursistas.js"  type="text/javascript"></script>