<div id='preLoader'></div>
<script type="text/javascript">var baseUrl = '<?php echo $this->baseUrl(); ?>';</script>
<style type="text/css">
    .btnPesquisar {
    	margin-left: 240px;
    	position: absolute;
    	
	}
	
	#form span{
	    width: 140px !important;
	}

	#form span.campoRequerido{
	    width: 125px !important;
	}
</style>
<?php
echo $this->formFilter;
echo $this->grid;
?>
<script src="<?php echo $this->baseUrl(); ?>/js/manutencao.configuracao.js"  type="text/javascript"></script>