<div id='preLoader'></div>
<script type="text/javascript">var baseUrl = '<?php echo $this->baseUrl(); ?>';</script>
<style type="text/css">
    .btnPesquisar {
    	margin-left: 240px;
    	position: absolute;
    	
	}
	
	#form span{
	    width: 140px !important;
	}

	#form span.campoRequerido{
	    width: 125px !important;
	}
</style>
<script src="<?php echo $this->baseUrl(); ?>/js/jquery.maskMoney.js"  type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/funcoes.js"  type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/jquery.maskedinput.js"  type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/util.js"  type="text/javascript"></script>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . '/css/grid.css'); ?>
<div>
    <?php
echo $this->form;
	?>
</div>