<div id='preLoader'></div>
<script type="text/javascript">var baseUrl = '<?php echo $this->baseUrl(); ?>';</script>
<style type="text/css">
    #preLoader {
	    width: 100%;
	    height: 100%;
	    margin: 0;
	    padding: 0;
	    background: #fff url(<?php echo $this->baseUrl(); ?>/img/ajax-loader.gif) no-repeat center center;
	    opacity: 0.60;
	    filter: alpha(opacity = 30);
	    -moz-opacity: 0.30;
	    position: absolute;
	    z-index: 999999;
	    display: none;
	}

	.errors li {
		width: 400px;
		color: #FF0000;
	}
    
    .btnPesquisar {
    	margin-left: 240px;
    	position: absolute;
    	
	}
	
	#form span{
	    width: 140px !important;
	}

	#form span.campoRequerido{
	    width: 125px !important;
	}
</style>
<div>
    <?php
echo $this->form;
	?>
</div>
<form>
	<div class="notas">Campo obrigatório</div>
</form>
<script src="<?php echo $this->baseUrl(); ?>/js/util.js"  type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/secretaria.turma.js"  type="text/javascript"></script>