<script type="text/javascript">

var baseUrl = '<?php echo $this->baseUrl(); ?>';
var perfilTutor =
<?php
$usuarioLogado = Zend_Auth::getInstance()->getIdentity();
$perfilUsuario = $usuarioLogado->credentials;
if ( in_array(Fnde_Sice_Business_Componentes::TUTOR, $perfilUsuario) ) {
	echo 1;
} else {
	echo 0;
}

?>

</script>
<style type="text/css">
	#preLoader {
	    width: 100%;
	    height: 100%;
	    margin: 0;
	    padding: 0;
	    background: #fff url(<?php echo $this->baseUrl(); ?>/img/ajax-loader.gif) no-repeat center center;
	    opacity: 0.60;
	    filter: alpha(opacity = 30);
	    -moz-opacity: 0.30;
	    position: absolute;
	    z-index: 999999;
	    display: none;
	}

	.errors li {
		width: 400px;
		color: #FF0000;
	}

</style>
<?php
echo $this->formFilter;
?>
<form>
	<div class="notas">Campo obrigatório</div>
</form>
<br clear="all" />
<?php

$arrHeader = array('ID', '<center>UF</center>', '<center>Município</center>', '<center>Curso</center>',
		'<center>Tutor</center>', '<center>Articulador</center>', '<center>Data início</center>',
		'<center>Data fim prevista</center>', '<center>Data finalização</center>',
		'<center>Situação</center>','<center>Configuração</center>');
if (count($this->rsRegistros)){
	$grid = new Fnde_View_Helper_DataTables();

	$grid->setMainAction($this->arrayMaisAcoes);
	$grid->setAutoCallJs(true);
	$grid->setActionColumn("<center>Ações</center>");
	$grid->setData($this->rsRegistros);
	$grid->setHeader($arrHeader);
	$grid->setHeaderActive(false);
	$grid->setTitle('Listagem de Turmas');
	$grid->setRowAction($this->rowAction);
	$grid->setId('NU_SEQ_TURMA');
	$grid->setRowInput(Fnde_View_Helper_DataTables::INPUT_TYPE_RADIO);
	$grid->setTableAttribs(array('id' => 'edit'));
	$grid->setColumnsHidden(array("NO_MESO_REGIAO", "NU_SEQ_CONFIGURACAO"));
	echo $grid;
}
?>
<script src="<?php echo $this->baseUrl(); ?>/js/util.js"  type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/secretaria.turma.js"  type="text/javascript"></script>