<script type="text/javascript">var baseUrl = '<?php echo $this->baseUrl(); ?>';</script>
<style type="text/css">
    #preLoader {
        width: 100%;
        height: 100%;
        margin: 0;
        padding: 0;
        background: #fff url(<?php echo $this->baseUrl(); ?>/img/ajax-loader.gif) no-repeat center center;
        opacity: 0.60;
        filter: alpha(opacity=30);
        -moz-opacity: 0.30;
        position: absolute;
        z-index: 999999;
        display: none;
    }

    .errors li {
        width: 400px;
        color: #FF0000;
    }

</style>

<?php echo $this->form; ?>

<!-- USADO PARA AUXILIAR NO DOWNLOAD DOS VARIOS CERTIFICADOS GERADOS. AÇÃO DO RODAPÉ DA GRID-->
<input id="ZIP_FILE" type="hidden" value="<?php echo $this->file ?>">

<div class="notas">Campo obrigatório</div>

<br clear="all"/>
<?php

if ($this->resultado):

    $rowAction = array_intersect_key(
        array(

            'certificado_cursista' => array('label' => 'Emitir Certificado',
                'url' => $this->Url(array('action' => 'gerar-para-cursista', 'NU_SEQ_USUARIO' => ''))
                    . '%s/NU_SEQ_TURMA/%s', 'params' => array('NU_SEQ_USUARIO', 'NU_SEQ_TURMA'),
                'attribs' => array('class' => 'icoDownload', 'title' => 'Emitir Certificado', 'target' => "_blank")),

            'certificado_tutor' => array('label' => 'Emitir Certificado',
                'url' => $this->Url(array('action' => 'tutor', 'NU_SEQ_USUARIO' => ''))
                    . '%s/NU_SEQ_CURSO/%s', 'params' => array('NU_SEQ_USUARIO', 'NU_SEQ_CURSO'),
                'attribs' => array('class' => 'icoDownload', 'title' => 'Emitir Certificado')),

            'declaracao_articulador' => array('label' => 'Emitir Declaração',
                'url' => $this->Url(array('action' => 'articulador', 'NU_SEQ_USUARIO' => ''))
                    . '%s/NU_SEQ_CURSO/%s', 'params' => array('NU_SEQ_USUARIO', 'NU_SEQ_CURSO'),
                'attribs' => array('class' => 'icoDownload', 'title' => 'Emitir Declaração')),

            'avaliar_curso' => array('label' => 'Avaliar Curso',
                'url' => $this->Url(
                        array('module' => 'avaliacaoinstitucional', 'controller' => 'avaliarcurso',
                            'action' => 'form', 'NU_SEQ_TURMA' => '')) . '%s/ST_CURSO_AVAL/%s/ST_TURMA/%s/DS_SITUACAO/%s/',
                'params' => array('NU_SEQ_TURMA', 'ST_CURSO_AVAL', 'ST_TURMA', 'DS_SITUACAO'),
                'attribs' => array('class' => 'icoAvaliar', 'title' => 'Avaliar Curso')),

            'notificar_cursista' => array('label' => 'Notificar Cursista',
                'url' => $this->Url(
                        array('module' => 'secretaria', 'controller' => 'notificarcursista',
                            'action' => 'notificarcursistaemitircert', 'NU_SEQ_TURMA' => '')) . '%s/ST_CURSO_AVAL/%s/ST_TURMA/%s/DS_SITUACAO/%s/',
                'params' => array('NU_SEQ_TURMA', 'ST_CURSO_AVAL', 'ST_TURMA', 'DS_SITUACAO'),
                'attribs' => array('class' => 'icoEncaminhar', 'title' => 'Notificar Cursista'))
        ),
        array_flip($this->botoes)
    );


    $grid = new Fnde_View_Helper_DataTables();

    if (isset($this->resultado[0]['NU_SEQ_USUARIO_NU_SEQ_TURMA'])) {

        $acoesRodape = array(
            "Emitir Certificado" => $this->Url(array('action' => 'gerar-varios-para-cursista')));

        $arrHeader = array('<center>UF</center>', '<center>Município</center>', '<center>Nome</center>',
            '<center>CPF</center>', '<center>Curso</center>', '<center>Data finalização</center>');

        $grid->setMainAction($acoesRodape);
        $grid->setId('NU_SEQ_USUARIO_NU_SEQ_TURMA');
        $grid->setRowInput(Fnde_View_Helper_DataTables::INPUT_TYPE_CHECKBOX);

    } else {

        $arrHeader = array('<center>UF</center>', '<center>Município</center>', '<center>Nome</center>',
            '<center>CPF</center>', '<center>Curso</center>');

        $grid->setId('USUARIO_CURSO');
    }

    $grid->setHeaderActive(false);
    $grid->setAutoCallJs(true);
    $grid->setActionColumn("<center>Ações</center>");
    $grid->setTitle($this->tituloGrid);
    $grid->setData($this->resultado)
        ->setHeader($arrHeader)
        ->setRowAction($rowAction)
        ->setColumnsHidden(array('USUARIO_CURSO', 'NU_SEQ_USUARIO_NU_SEQ_TURMA', 'NU_MATRICULA', 'NU_SEQ_TURMA', 'NU_SEQ_USUARIO', 'NU_SEQ_CURSO', 'DS_SITUACAO', 'ST_CURSO_AVAL', 'ST_TURMA'))
        ->setTableAttribs(array('id' => 'tbCursista'));
    echo $grid;

endif;
?>
<script src="<?php echo $this->baseUrl(); ?>/js/util.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/secretaria.emitircertificado.js" type="text/javascript"></script>