<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt-BR" lang="pt-BR">
<head>

<meta http-equiv="X-UA-Compatible" content="IE=8" />
<meta http-equiv="Pragma" content="no-cache" />
<meta http-equiv="Expires" content="-1" />
<meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1" />
<meta http-equiv="Content-Language" content="pt-BR" />
<meta name="keywords" content="Palavras-chave, separadas, por, virgula" />
<meta name="author"
	content="FNDE - Fundo Nacional de Desenvolvimento da Educação" />
<meta name="robots" content="index, no-follow" />
<meta name="title" content="FNDE :  " />
<meta name="description" content="Sice" />
<title>FNDE: sice v0.0.69</title>
<link type="image/x-icon" rel="shortcut icon"
	href="/static/images/interface/icone/favicon.ico" />
<link href="/static/css/fnde.min.css" media="screen" rel="stylesheet"
	type="text/css" />
<!--[if lt IE 8]>
        <link type="text/css" href="/static/css/ie-fix.css" rel="stylesheet" />
        <![endif]-->
<style type="text/css">

	body, form, #conteudo form {
	margin: 0px;
	padding: 0px;
	}
	
	
	

</style>	
	
<script type="text/javascript" src="/static/js/fnde.script.min.js"></script>
</head>
<body style="margin: 0; padding: 0;"  >
	<?php echo $this->message(( array ) $this->message); ?>
	<div id="preLoader"></div>
	<script type="text/javascript">var baseUrl = '<?php echo $this->baseUrl(); ?>';</script>
	<div id="conteudo" style="background: none;">
		<?php
echo $this->form;
		?>
		<div class="notas">Campo obrigatório</div>
		<script src="<?php echo $this->baseUrl(); ?>/js/secretaria.cursista.js" type="text/javascript"></script>
	</div>
</body>
</html>
